#!/usr/bin/env bash
# Initialises a REPORT from the real state: git context, a real test run, a
# real audit, a real drift check.
#
#   ./scripts/report.sh 002 seat-history
#
# It records what happened. It never writes a result it did not obtain: if
# the suite fails, the report says the suite failed. The sections a human
# must fill are left as explicit TODO markers, never pre-filled with a guess.
set -euo pipefail
cd "$(dirname "$0")/.."

NNN="${1:?usage: report.sh <spec-number> <slug>}"
SLUG="${2:?usage: report.sh <spec-number> <slug>}"
OUT="docs/reports/REPORT-${NNN}-${SLUG}.md"
[ -e "$OUT" ] && { echo "refusing to overwrite $OUT"; exit 1; }

BRANCH=$(git rev-parse --abbrev-ref HEAD)
HEAD_SHA=$(git rev-parse --short HEAD)
BASE=$(git merge-base master HEAD 2>/dev/null || echo "(no master)")
BASE_SHORT=$(git rev-parse --short "$BASE" 2>/dev/null || echo "-")

echo "· running the suite"
TEST_LOG=$(mktemp)
if npm test >"$TEST_LOG" 2>&1; then TEST_STATUS="pass"; else TEST_STATUS="FAIL"; fi
COUNTS=$({ grep -E '^. (tests|pass|fail) ' "$TEST_LOG" || true; } | tr -s ' ' | sed 's/^. //' | tr '\n' ',' | sed 's/,$//; s/,/, /g')
[ -z "$COUNTS" ] && COUNTS="unparsed — see the log"

echo "  $TEST_STATUS — $COUNTS"

echo "· audit"
AUDIT_LOG=$(mktemp); ./scripts/audit.sh >"$AUDIT_LOG" 2>&1 || true

echo "· drift"
DRIFT_LOG=$(mktemp)
if ./scripts/drift.sh >"$DRIFT_LOG" 2>&1; then DRIFT_STATUS="no drift"; else DRIFT_STATUS="DRIFT FOUND"; fi
echo "  $DRIFT_STATUS"

{
  echo "# REPORT — SPEC-${NNN}"
  echo
  echo "**SPEC executed:** docs/specs/SPEC-${NNN}-${SLUG}.md"
  echo "**Branch:** \`${BRANCH}\`"
  echo "**Starting commit:** \`${BASE_SHORT}\`"
  echo "**HEAD at report time:** \`${HEAD_SHA}\`"
  echo "**Date:** $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo
  echo "Generated by \`scripts/report.sh\`. Measured sections are filled from"
  echo "real runs. Sections marked TODO require a human — leave nothing guessed."
  echo
  echo "## 1. Overall result"
  echo
  echo "TODO — complete · partial · blocked · abandoned, then one sentence."
  echo
  echo "## 2. Summary"
  echo
  echo "TODO"
  echo
  echo "## 3. Files created"
  echo
  git status --porcelain | awk '/^\?\?/ {print "- `" $2 "`"}' || true
  echo
  echo "## 4. Files modified"
  echo
  if [ "$BASE_SHORT" != "-" ]; then
    git diff --stat "$BASE" HEAD | sed 's/^/    /' || true
    echo
    echo "Uncommitted:"
    echo
    git diff --stat | sed 's/^/    /' || true
  fi
  echo
  echo "## 5. Tests executed"
  echo
  echo "| Command | Result | Measured |"
  echo "|---|---|---|"
  echo "| \`npm test\` | **${TEST_STATUS}** | ${COUNTS} |"
  echo
  if [ "$TEST_STATUS" = "FAIL" ]; then
    echo "Failures:"
    echo
    echo '```'
    grep -E '^not ok|error:' "$TEST_LOG" | head -20
    echo '```'
    echo
  fi
  echo "New tests proven to bite: TODO — name each one and how it was seen failing."
  echo
  echo "## 6. Audit"
  echo
  echo '```'
  cat "$AUDIT_LOG"
  echo '```'
  echo
  echo "## 7. Drift check"
  echo
  echo "Result: **${DRIFT_STATUS}**"
  echo
  echo '```'
  cat "$DRIFT_LOG"
  echo '```'
  echo
  for s in "8. Invariants added" "9. Gaps" "10. Risks" \
           "11. Requires human validation" "12. Still manual" "13. Recommended next step"; do
    echo "## $s"; echo; echo "TODO"; echo
  done
} > "$OUT"

rm -f "$TEST_LOG" "$AUDIT_LOG" "$DRIFT_LOG"
echo
echo "written: $OUT"
echo "Fill every TODO before handing this over. Do not delete a TODO you did not answer."
